### ISSUE TITLE
Providing a dataset to the fuseki instance

### ISSUE THREAD

**Issue by wood-chris** [AtomGraph/fuseki-docker#1]
I managed to build a fuseki container from your Dockerfile, but it seems you need to provide a dataset when running `docker run`. Does this need to be a TDB? Can the dataset be provided as a command line argument or should it be specified by modifying the Dockerfile?

**Comment by namedgraph** [comment]
I've pushed an updated README -- can you check if it clarifies the usage?

The Dockerfile comes from this thread:
https://mail-archives.apache.org/mod_mbox/jena-users/201810.mbox/%3C6a0b7cb8-110b-44cb-7f54-4bdd33d893e1%40apache.org%3E

**Comment by namedgraph** [comment]
@wood-chris did it help?

**Comment by wood-chris** [comment]
I had a very quick go at running it in the same way as the other container, but I get an error 

> No dataset specified on the command line.

At the moment, I've only got a ttl file, rather than a tdb; the fuseki admin interface allows a ttl file to be uploaded - I guess I need to use tdbloader2 to create a dataset that I can then pass to an instance of this image?

**Comment by namedgraph** [comment]
Can you try what the README says:

    docker run --rm atomgraph/fuseki --mem /ds

**Comment by wood-chris** [comment]
Yes - I wasn't expecting an in-memory db to be a mandatory requirement to run it :)

There seems to be no admin console available, all standard URLs (including the SPARQL endpoint) on `localhost:3030` return 404 error

**Comment by namedgraph** [comment]
If I run with `--file`

    docker run --rm -p 3030:3030 -v $(pwd):/usr/share/data atomgraph/fuseki --file=/usr/share/data/smth.nt /ds

then I can access the endpoints, e.g. http://localhost:3030/ds/sparql?query=select%20*%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D returns a result.

With `--mem` I get 404 on http://localhost:3030/ds/sparql, but the query still works on http://localhost:3030/ds/sparql?query=select%20*%20%7B%20%3Fs%20%3Fp%20%3Fo%20%7D (returns no result).

As for UI, I think what is packaged here is the server version without UI:
https://jena.apache.org/documentation/fuseki2/fuseki-run.html#fuseki-server

I'll update the README again.

**Comment by namedgraph** [comment]
README is updated once again, hopefully it helps.

You're not on Windows, are you? Because there are extra things involved with slash escaping in paths etc...

**Comment by wood-chris** [comment]
Ah, ok. I'm not massively familiar with Docker (yet). Is the path in `--file` on the host or in the container?

**Comment by namedgraph** [comment]
`--file` in the container, because that's where Fuseki will look for it.
Which means you have to mount it from the host when running.

**Comment by wood-chris** [comment]
Ah, I've just realised that default jena doesn't include SPARQLer (which is what I was thinking of!) - that'll be why the URL I was expecting to show a HTML view of a SPARQL endpoint returns a 404! (I've raised a query with Jena about this, because I thought SPARQLer was packaged with Fuseki)
