### ISSUE TITLE
Base image on linked-solutions/fuseki-base

### ISSUE THREAD

**Issue by retog** [AtomGraph/fuseki-docker#2]
linked-solutions/fuseki-base is meant to provide a base image for various fuseki docker distributions. It uses maven so can be always use the latest fuseki version, see https://github.com/linked-solutions/fuseki-base.

**Comment by namedgraph** [comment]
@retog this image is now using the [`Dockerfile` that ships with Fuseki](https://github.com/apache/jena/blob/31dc0d328c4858401e5d3fa99702c97eba0383a0/jena-fuseki2/jena-fuseki-docker/Dockerfile).
