### ISSUE TITLE
Add semver tags to docker hub builds?

### ISSUE THREAD

**Issue by blake-regalia** [AtomGraph/fuseki-docker#4]
Would be nice to have tags for the builds that correspond to fuseki version, including tag for latest major release, e.g., `atomgraph/fuseki:3.14` and `atomgraph/fuseki:3`.

**Comment by namedgraph** [comment]
@blake-regalia any advice on how to do that? :)

**Comment by blake-regalia** [comment]
On docker hub, under Builds > Configure Automated Builds... you can add build rules to match git tags using regular expressions (e.g., `/^v([0-9]+)\.([0-9]+)\.([0-9]+)$/`) and then variable substitution, like this:
<img width="1239" alt="Screen Shot 2020-03-10 at 4 00 49 PM" src="https://user-images.githubusercontent.com/1456400/76366953-ac3f8480-62e8-11ea-85db-90817f689537.png">

Then, after pushing the git tag `v3.14.0` to GH:
 - `{\1}.{\2}.{\3}` would create the docker tag `:3.14.0`
 - `{\1}.{\2}` would create the docker tag `:3.14`
 - `{\1}` would create the docker tag `:3`

**Comment by namedgraph** [comment]
@blake-regalia I've now configured the rules you provided in Docker Hub and pushed tag `v4.6.0`. Lets see what happens.
Sorry it took 2.5 years :)

**Comment by namedgraph** [comment]
Looks like it works:
https://hub.docker.com/layers/atomgraph/fuseki/4.6.0/images/sha256-e22e75e93b21f8421a1cdae35035eac148083b9c9585e0db16a2b9d19d8ff794?context=explore
